name: Build Prod Image

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v2

      - name: 🏗️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 🔑 Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🎃 Set up outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: ⚓ Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          # build-args: |
          #   arg1=value1
          #   arg2=value2
          # cache-from: type=registry,ref=mashirozx/mastodon:alpha
          # cache-to: type=inline
          # tags: mashirozx/mastodon:alpha
          tags: |
            twoheart/mastodon:latest
            # mashirozx/mastodon:latest
            # mashirozx/mastodon:sha-${{steps.vars.outputs.sha_short}}

      # - name: ⚓ Build and push Docker images
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: mashirozx/mastodon
      #     tags: alpha
